# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'GitSuperStars' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitSuperStars
  pod 'Moya', '~> 13.0.1'
  pod 'Kingfisher', '~> 5.7.1'

end
