# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'GitSuperStars' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitSuperStars
  pod 'Kingfisher', '~> 5.7.1'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'GitSuperStarsTests' do
    inherit! :search_paths
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end
  
end
